<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Class-Lesson" data-toc-modified-id="Class-Lesson-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Class Lesson</a></span><ul class="toc-item"><li><span><a href="#How-many-numbers-match-the-mask?" data-toc-modified-id="How-many-numbers-match-the-mask?-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>How many numbers match the mask?</a></span></li><li><span><a href="#Sum-all-the-numbers-that-match-the-mask-(x->-950)" data-toc-modified-id="Sum-all-the-numbers-that-match-the-mask-(x->-950)-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Sum all the numbers that match the mask (x &gt; 950)</a></span></li></ul></li><li><span><a href="#Exercises" data-toc-modified-id="Exercises-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Exercises</a></span><ul class="toc-item"><li><span><a href="#How-many-negative-numbers-are-there?" data-toc-modified-id="How-many-negative-numbers-are-there?-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>How many negative numbers are there?</a></span></li><li><span><a href="#How-many-positive-numbers-are-there?" data-toc-modified-id="How-many-positive-numbers-are-there?-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>How many positive numbers are there?</a></span></li><li><span><a href="#How-many-even-positive-numbers-are-there?" data-toc-modified-id="How-many-even-positive-numbers-are-there?-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>How many even positive numbers are there?</a></span></li><li><span><a href="#If-you-were-to-add-3-to-each-data-point,-how-many-positive-numbers-would-there-be?" data-toc-modified-id="If-you-were-to-add-3-to-each-data-point,-how-many-positive-numbers-would-there-be?-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>If you were to add 3 to each data point, how many positive numbers would there be?</a></span></li><li><span><a href="#If-you-squared-each-number,-what-would-the-new-mean-and-standard-deviation-be?" data-toc-modified-id="If-you-squared-each-number,-what-would-the-new-mean-and-standard-deviation-be?-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>If you squared each number, what would the new mean and standard deviation be?</a></span></li><li><span><a href="#A-common-statistical-operation-on-a-dataset-is-centering.-This-means-to-adjust-the-data-such-that-the-center-of-the-data-is-at-0.-This-is-done-by-subtracting-the-mean-from-each-data-point.-Center-the-data-set." data-toc-modified-id="A-common-statistical-operation-on-a-dataset-is-centering.-This-means-to-adjust-the-data-such-that-the-center-of-the-data-is-at-0.-This-is-done-by-subtracting-the-mean-from-each-data-point.-Center-the-data-set.-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>A common statistical operation on a dataset is centering. This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.</a></span></li><li><span><a href="#Calculate-the-z-score-for-each-data-point.-Recall-that-the-z-score-is-given-by:" data-toc-modified-id="Calculate-the-z-score-for-each-data-point.-Recall-that-the-z-score-is-given-by:-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Calculate the z-score for each data point. Recall that the z-score is given by:</a></span></li></ul></li><li><span><a href="#More-Exercises" data-toc-modified-id="More-Exercises-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>More Exercises</a></span><ul class="toc-item"><li><span><a href="#Exercise-1---Make-a-variable-called-sum_of_a-to-hold-the-sum-of-all-the-numbers-in-above-list." data-toc-modified-id="Exercise-1---Make-a-variable-called-sum_of_a-to-hold-the-sum-of-all-the-numbers-in-above-list.-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list.</a></span><ul class="toc-item"><li><span><a href="#Using-numpy-.sum()" data-toc-modified-id="Using-numpy-.sum()-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>Using numpy <code>.sum()</code></a></span></li></ul></li><li><span><a href="#Exercise-2---Make-a-variable-named-min_of_a-to-hold-the-minimum-of-all-the-numbers-in-the-above-list." data-toc-modified-id="Exercise-2---Make-a-variable-named-min_of_a-to-hold-the-minimum-of-all-the-numbers-in-the-above-list.-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list.</a></span></li><li><span><a href="#Exercise-3---Make-a-variable-named-max_of_a-to-hold-the-max-number-of-all-the-numbers-in-the-above-list" data-toc-modified-id="Exercise-3---Make-a-variable-named-max_of_a-to-hold-the-max-number-of-all-the-numbers-in-the-above-list-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list</a></span><ul class="toc-item"><li><span><a href="#Using-numpy-.max()" data-toc-modified-id="Using-numpy-.max()-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>Using numpy .max()</a></span></li></ul></li><li><span><a href="#Exercise-4---Make-a-variable-named-mean_of_a-to-hold-the-average-of-all-the-numbers-in-the-above-list." data-toc-modified-id="Exercise-4---Make-a-variable-named-mean_of_a-to-hold-the-average-of-all-the-numbers-in-the-above-list.-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list.</a></span><ul class="toc-item"><li><span><a href="#Using-numpy-.mean()" data-toc-modified-id="Using-numpy-.mean()-3.4.1"><span class="toc-item-num">3.4.1&nbsp;&nbsp;</span>Using numpy .mean()</a></span></li></ul></li><li><span><a href="#Exercise-5---Make-a-variable-named-product_of_a-to-hold-the-product-of-multiplying-all-the-numbers-in-the-above-list-together." data-toc-modified-id="Exercise-5---Make-a-variable-named-product_of_a-to-hold-the-product-of-multiplying-all-the-numbers-in-the-above-list-together.-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together.</a></span><ul class="toc-item"><li><span><a href="#Using-numpy-.prod()" data-toc-modified-id="Using-numpy-.prod()-3.5.1"><span class="toc-item-num">3.5.1&nbsp;&nbsp;</span>Using numpy .prod()</a></span></li></ul></li><li><span><a href="#Exercise-6---Make-a-variable-named-squares_of_a.-It-should-hold-each-number-in-a-squared-like-[1,-4,-9,-16,-25...]" data-toc-modified-id="Exercise-6---Make-a-variable-named-squares_of_a.-It-should-hold-each-number-in-a-squared-like-[1,-4,-9,-16,-25...]-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]</a></span><ul class="toc-item"><li><span><a href="#Using-numpy" data-toc-modified-id="Using-numpy-3.6.1"><span class="toc-item-num">3.6.1&nbsp;&nbsp;</span>Using numpy</a></span></li></ul></li><li><span><a href="#Exercise-7---Make-a-variable-named-odds_in_a.-It-should-hold-only-the-odd-numbers." data-toc-modified-id="Exercise-7---Make-a-variable-named-odds_in_a.-It-should-hold-only-the-odd-numbers.-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers.</a></span><ul class="toc-item"><li><span><a href="#Using-numpy" data-toc-modified-id="Using-numpy-3.7.1"><span class="toc-item-num">3.7.1&nbsp;&nbsp;</span>Using numpy</a></span></li></ul></li><li><span><a href="#Exercise-8---Make-a-variable-named-evens_in_a.-It-should-hold-only-the-evens." data-toc-modified-id="Exercise-8---Make-a-variable-named-evens_in_a.-It-should-hold-only-the-evens.-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.</a></span><ul class="toc-item"><li><span><a href="#Using-numpy" data-toc-modified-id="Using-numpy-3.8.1"><span class="toc-item-num">3.8.1&nbsp;&nbsp;</span>Using numpy</a></span></li></ul></li></ul></li></ul></div>

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

from pydataset import data

import warnings
warnings.filterwarnings('ignore')

## Class Lesson

In [3]:
x = np.arange(-1000, 1000)

In [4]:
mask = x > 950

In [5]:
mask

array([False, False, False, ...,  True,  True,  True])

In [6]:
x[mask]

array([951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963,
       964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976,
       977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989,
       990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

### How many numbers match the mask?

In [7]:
mask.sum()

49

### Sum all the numbers that match the mask (x > 950)

In [8]:
x[mask].sum()

47775

In [9]:
x[mask].mean()

975.0

In [10]:
higher_than_950 = x[mask]

In [11]:
higher_than_950.min()

951

In [12]:
higher_than_950.max()

999

In [13]:
# returns the index of the highest number

higher_than_950.argmax()

48

In [14]:
higher_than_950[higher_than_950.argmax()]

999

In [15]:
# convert array to a Pandas Series to use .iloc indexer

higher_series = pd.Series(higher_than_950)
type(higher_series)

pandas.core.series.Series

In [16]:
# return the value at the index of higher_than_950.argmax()

higher_series.iloc[higher_than_950.argmax()]

999

## Exercises

In [65]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

### How many negative numbers are there?

In [66]:
neg_bool = a < 0
neg_bool

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [67]:
neg_bool.sum()

4

### How many positive numbers are there?



In [68]:
pos_bool = a > 0
pos_bool

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True, False])

In [69]:
pos_bool.sum()

5

### How many even positive numbers are there?

In [70]:
even_bool = a % 2 == 0
even_bool

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True, False, False])

In [72]:
even_pos_bool = even_bool & pos_bool

In [73]:
even_pos_bool.sum()

3

### If you were to add 3 to each data point, how many positive numbers would there be?

In [26]:
new_a = a + 3
pos_new_a = new_a > 0
pos_new_a.sum()

10

### If you squared each number, what would the new mean and standard deviation be?

In [29]:
squared_a = a ** 2
new_mean = squared_a.mean()
new_mean

74.0

In [30]:
new_std = squared_a.std()
new_std

144.0243035046516

### A common statistical operation on a dataset is centering. This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.

In [34]:
a_mean = a.mean()
centered_data = a - a_mean
centered_data

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

### Calculate the z-score for each data point. Recall that the z-score is given by:



In [36]:
z_score = centered_data / a.std()
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

## More Exercises

In [127]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list.

In [128]:
total = 0
for ele in range(0, len(a)):
    total = total + a[ele]
print(total)

55


In [129]:
array_a = np.array(a)
array_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Using numpy `.sum()`

In [130]:
array_a.sum()

55

### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list.

In [131]:
a.sort()
min_of_a = a[0]
min_of_a

1

### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [132]:
a.sort(reverse=True)
max_of_a = a[0]
max_of_a

10

#### Using numpy .max()

In [133]:
array_a.max()

10

### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list.

In [134]:
total = 0
for ele in range(0, len(a)):
    total = total + a[ele]
length = len(a)
mean_of_a = total / length

mean_of_a

5.5

#### Using numpy .mean()

In [135]:
array_a.mean()

5.5

### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together.

In [136]:
prod = 1
for ele in range(0, len(a)):
    prod = prod * a[ele]
product_of_a = prod
product_of_a

3628800

#### Using numpy .prod()

In [137]:
product_of_a = array_a.prod()
product_of_a

3628800

### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [143]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

squares_of_a = []

for ele in range(0, len(a)):
    squares_of_a.append(a[ele] ** 2)

squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#### Using numpy

In [139]:
squares_of_a = array_a**2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers.

In [144]:
odds_of_a = []
for ele in range(0, len(a)):
    if a[ele] % 2 != 0:
        odds_of_a.append(a[ele])
odds_of_a

[1, 3, 5, 7, 9]

#### Using numpy

In [147]:
odds_of_a = array_a[array_a % 2 != 0]
odds_of_a

array([1, 3, 5, 7, 9])

### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [149]:
evens_in_a = [a[ele] for ele in range(0, len(a)) if a[ele] % 2 == 0]

[2, 4, 6, 8, 10]

#### Using numpy

In [148]:
evens_in_a = array_a[array_a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])